app:
  kafka:
    topic: ${KAFKA_TOPIC_TRANSFER_EVENTS:transfer-events}

management:
  tracing:
    sampling:
      probability: 1.0
    export:
      zipkin:
        enabled: true
        endpoint: http://127.0.0.1:9411/api/v2/spans

spring:
  application:
    name: transfer
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: transfer-service
            client-secret: ${CLIENT_SECRET}
            scope: openid
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}
server:
  port: ${SERVER_PORT:8083}
