spring:
  application:
    name: cash

  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: cash-service
            client-secret: ${CLIENT_SECRET}
            scope: openid
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}

      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}

server:
  port: ${SERVER_PORT:8081}

logging:
  level:
    org.springframework.web.client.RestClient: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.security: DEBUG