server:
  port: ${SERVER_PORT:8080}

app:
  kafka:
    topic: ${KAFKA_TOPIC_ACCOUNTS_EVENTS:accounts-events}

management:
  tracing:
    sampling:
      probability: 1.0
    export:
      zipkin:
        enabled: true
        endpoint: ${MANAGEMENT_TRACING_EXPORT_ZIPKIN_ENDPOINT:http://127.0.0.1:9411/api/v2/spans}

spring:
  application:
    name: accounts
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer


  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: accounts-service
            client-secret: ${CLIENT_SECRET}
            scope: openid
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: ${SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI}
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}

  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog-master.yaml
    url: ${SPRING_DATASOURCE_URL}
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    default-schema: public

logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "
  level:
    org.springframework.boot.micrometer.tracing: TRACE
    org.springframework.boot.micrometer.tracing.brave: TRACE
    io.micrometer.tracing: TRACE
    io.micrometer.observation: TRACE
    brave: DEBUG
    zipkin2.reporter: DEBUG
