apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-global-config
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.global.environment | quote }}

  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: {{ .Values.global.keycloak.issuerUri | quote }}
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: {{ .Values.global.keycloak.jwkSetUri | quote }}

  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI: {{ .Values.global.keycloak.issuerUri | quote }}

  SPRING_CLOUD_CONSUL_CONFIG_ENABLED: "false"
  SPRING_CLOUD_CONSUL_CONFIG_IMPORT_CHECK_ENABLED: "false"

  SPRING_KAFKA_BOOTSTRAP_SERVERS: "{{ .Values.global.kafka.name }}:{{ .Values.global.kafka.port }}"
  KAFKA_BOOTSTRAP_SERVERS: "{{ .Values.global.kafka.name }}:{{ .Values.global.kafka.port }}"

  KAFKA_TOPIC_CASH_EVENTS: {{ .Values.global.kafka.topics.cashEvents | quote }}
  KAFKA_TOPIC_TRANSFER_EVENTS: {{ .Values.global.kafka.topics.transferEvents | quote }}
  KAFKA_TOPIC_ACCOUNTS_EVENTS: {{ .Values.global.kafka.topics.accountsEvents | quote }}