{{- if and .Values.front .Values.front.keycloak }}
apiVersion: v1
kind: Secret
metadata:
  name: front-secret
type: Opaque
stringData:
  CLIENT_SECRET: {{ .Values.front.keycloak.clientSecret | quote }}
{{- end }}