{{- if .Values.front.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.front.name }}
  labels:
    app: {{ .Values.front.name }}
    {{- include "banking-backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.front.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.front.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.front.name }}
    spec:
      containers:
        - name: {{ .Values.front.name }}
          image: {{ .Values.front.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy | default "Never" }}
          ports:
            - name: http
              containerPort: {{ .Values.front.port }}


          env:
            - name: SERVER_PORT
              value: {{ .Values.front.port | quote }}

            - name: APP_GATEWAY_BASE_URL
              value: "http://{{ .Values.gateway.name }}:{{ .Values.gateway.service.port }}"

            - name: MANAGEMENT_TRACING_EXPORT_ZIPKIN_ENDPOINT
              value: "http://{{ .Values.global.zipkin.name }}:{{ .Values.global.zipkin.port }}/api/v2/spans"

            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: {{ .Values.global.keycloak.issuerUri | quote }}

            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: front-secret
                  key: CLIENT_SECRET

            - name: JAVA_TOOL_OPTIONS
              value: "-Xms128m -Xmx256m"

            - name: APP_LOGSTASH_HOST
              value: {{ .Values.global.elk.logstash.name | quote }}

            - name: APP_LOGSTASH_PORT
              value: {{ .Values.global.elk.logstash.port | quote }}

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 40
            periodSeconds: 20
{{- end }}