{{- if .Values.global.kafka.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.kafka.name }}
  labels:
    app: {{ .Values.global.kafka.name }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: {{ .Values.global.kafka.name }}
  ports:
    - name: kafka
      port: {{ .Values.global.kafka.port }}
      targetPort: kafka
    - name: controller
      port: {{ .Values.global.kafka.controllerPort }}
      targetPort: controller
{{- end }}