{{- range $key, $svc := .Values.services }}
{{- if and $svc.db $svc.db.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $svc.db.name }}-secret
type: Opaque
stringData:
  username: {{ $svc.db.username | quote }}
  password: {{ $svc.db.password | quote }}
---
{{- end }}

{{- if $svc.keycloak }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $svc.name }}-secret
type: Opaque
stringData:
  CLIENT_SECRET: {{ $svc.keycloak.clientSecret | quote }}
---
{{- end }}
{{- end }}