global:
  environment: k8s
  imagePullPolicy: Never


  keycloak:
    issuerUri: ""
    jwkSetUri: ""

  kafka:
    imagePullPolicy: IfNotPresent
    enabled: true
    name: kafka
    image: apache/kafka:3.7.1
    port: 9092
    controllerPort: 9093
    storage: 2Gi
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: "1"
        memory: 1Gi
    topics:
      cashEvents: cash-events
      transferEvents: transfer-events
      accountsEvents: accounts-events
    topicDefinitions:
      - name: cash-events
        partitions: 1
        replicationFactor: 1
      - name: transfer-events
        partitions: 1
        replicationFactor: 1
      - name: accounts-events
        partitions: 1
        replicationFactor: 1

  zipkin:
    enabled: true
    name: zipkin
    image: openzipkin/zipkin:3.5
    port: 9411
    imagePullPolicy: IfNotPresent
    service:
      type: NodePort
      nodePort: 30411

  prometheus:
    enabled: true
    name: prometheus
    image: prom/prometheus:v2.55.1
    port: 9090
    imagePullPolicy: IfNotPresent
    service:
      type: NodePort
      nodePort: 30090

  grafana:
    enabled: true
    name: grafana
    image: grafana/grafana:11.5.2
    port: 3000
    adminUser: admin
    adminPassword: admin
    service:
      type: NodePort
      port: 80
      nodePort: 30030

  elk:
    enabled: true

    elasticsearch:
      name: elasticsearch
      image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
      port: 9200
      service:
        type: ClusterIP
        port: 9200

    logstash:
      name: logstash
      image: docker.elastic.co/logstash/logstash:8.15.3
      port: 5000
      service:
        type: ClusterIP
        port: 5000

    kibana:
      name: kibana
      image: docker.elastic.co/kibana/kibana:8.15.3
      port: 5601
      service:
        type: NodePort
        port: 80
        nodePort: 30601

gateway:
  name: gateway
  image: gateway:1.0.11
  port: 8080
  replicas: 1

  service:
    type: NodePort
    port: 80
    nodePort: 30080

front:
  enabled: true
  name: front
  image: front:1.0.11
  port: 8084
  replicas: 1
  keycloak:
    clientSecret: ""
  service:
    type: NodePort
    port: 80
    nodePort: 30084

services:
  accounts:
    name: accounts-service
    image: accounts-service:1.0.11
    port: 8080
    replicas: 1
    keycloak:
      clientSecret: ""
    kafka:
      topic: accounts-events
      producer:
        enabled: true
    db:
      enabled: true
      name: accounts-db
      image: postgres:16
      port: 5432
      database: accountsdb
      username: ""
      password: ""
      storage: 2Gi
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi

  cash:
    name: cash-service
    image: cash-service:1.0.11
    port: 8080
    replicas: 1
    keycloak:
      clientSecret: ""
    kafka:
      topic: cash-events
      producer:
        enabled: true

  transfer:
    name: transfer-service
    image: transfer-service:1.0.11
    port: 8080
    replicas: 1
    keycloak:
      clientSecret: ""
    kafka:
      topic: transfer-events
      producer:
        enabled: true

  notifications:
    name: notifications-service
    image: notifications-service:1.0.11
    port: 8080
    replicas: 1
    keycloak:
      clientSecret: ""