global:
  environment: k8s
  imagePullPolicy: Never


  keycloak:
    issuerUri: ""
    jwkSetUri: ""

  kafka:
    imagePullPolicy: IfNotPresent
    enabled: true
    name: kafka
    image: apache/kafka:3.7.1
    port: 9092
    controllerPort: 9093
    storage: 2Gi
    topics:
      cashEvents: cash-events
      transferEvents: transfer-events
      accountsEvents: accounts-events
    topicDefinitions:
      - name: cash-events
        partitions: 1
        replicationFactor: 1
      - name: transfer-events
        partitions: 1
        replicationFactor: 1
      - name: accounts-events
        partitions: 1
        replicationFactor: 1

gateway:
  name: gateway
  image: gateway:1.0.1
  port: 8080
  replicas: 1

  service:
    type: NodePort
    port: 80
    nodePort: 30080

services:
  accounts:
    name: accounts-service
    image: accounts-service:1.0.1
    port: 8080
    replicas: 1
    keycloak:
      clientSecret: ""
    kafka:
      topic: accounts-events
      producer:
        enabled: true
    db:
      enabled: true
      name: accounts-db
      image: postgres:16
      port: 5432
      database: accountsdb
      username: ""
      password: ""
      storage: 2Gi


  cash:
    name: cash-service
    image: cash-service:1.0.1
    port: 8080
    replicas: 1
    keycloak:
      clientSecret: ""
    kafka:
      topic: cash-events
      producer:
        enabled: true

  transfer:
    name: transfer-service
    image: transfer-service:1.0.1
    port: 8080
    replicas: 1
    keycloak:
      clientSecret: ""
    kafka:
      topic: transfer-events
      producer:
        enabled: true

  notifications:
    name: notifications-service
    image: notifications-service:1.0.2
    port: 8080
    replicas: 1
    keycloak:
      clientSecret: ""