input {
  tcp {
    port => 5000
    codec => json_lines
  }
}
filter {
  mutate {
    add_field => {
      "environment" => "k8s"
    }
  }
  if [message] {
    mutate {
      gsub => [
        "message", "password=[^,\\s]+", "password=***",
        "message", "clientSecret=[^,\\s]+", "clientSecret=***",
        "message", "accountNumber=[0-9]+", "accountNumber=***",
        "message", "cardNumber=[0-9]+", "cardNumber=***"
      ]
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "banking-logs-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}